(executable
 (name public_consumer)
 (modules public_consumer)
 (libraries observe))

(executable
 (name ppx_consumer)
 (modules ppx_consumer)
 (libraries observe)
 (preprocess
  (pps observe.ppx)))

(executable
 (name adapter_consumer)
 (modules adapter_consumer)
 (libraries observe-lwt-unix observe-lwt observe-unix observe lwt))
