(alias
 (name observe-core-contracts)
 (package observe)
 (deps
  (alias public/observe-public-contracts)
  (alias formatter/observe-formatter-contracts)
  (alias capture/observe-capture-contracts)
  (alias runtime/observe-runtime-state)
  (alias concurrency/observe-concurrency-smoke)
  (alias ppx/observe-ppx-contracts)))

(alias
 (name runtest)
 (package observe)
 (deps
  (alias observe-core-contracts)))

(alias
 (name observe-contracts)
 (deps
  (alias observe-core-contracts)
  (alias lwt/observe-lwt-contracts)
  (alias unix/observe-unix-contracts)
  (alias lwt/unix/observe-lwt-unix-contracts)))
