(executable
 (name simple)
 (libraries observe observe-lwt-unix lwt lwt.unix)
 (preprocess
  (pps observe.ppx)))

(rule
 (alias observe-examples)
 (package observe-lwt-unix)
 (action
  (run %{exe:simple.exe})))

(executable
 (name filesystem)
 (libraries observe observe-lwt-unix observe-fs-lwt-unix lwt lwt.unix))

(alias
 (name observe-fs-examples)
 (package observe-fs-lwt-unix)
 (deps filesystem.exe))
