(executable
 (name test_unix_platform)
 (modules test_unix_platform)
 (libraries observe-unix observe alcotest unix))

(rule
 (alias observe-unix-contracts)
 (package observe-unix)
 (deps test_unix_platform.exe)
 (action
  (run %{exe:test_unix_platform.exe})))

(alias
 (name runtest)
 (package observe-unix)
 (deps
  (alias observe-unix-contracts)))
